name: CD - Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy Bundle to Target"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Databricks Bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Deploying Databricks Asset Bundle..."
          databricks bundle deploy